ALTER TABLE users ADD COLUMN wins INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN losses INT NOT NULL DEFAULT 0;
ALTER TABLE matches ADD COLUMN winner_rating_delta INT DEFAULT 0;
ALTER TABLE matches ADD COLUMN loser_rating_delta INT DEFAULT 0;
